### ISSUE TITLE
Content: Images

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2-blue-gum#12]
**Status:** Design draft. Ready for discussion and coding.

**Designs:**
[midsize content.pdf](https://github.com/serlo/athene2-blue-gum/files/3152488/midsize.content.pdf)
[mobile content.pdf](https://github.com/serlo/athene2-blue-gum/files/3152489/mobile.content.pdf)

Follow ups: There might be more image components (gallery, aside images) but this is enough as a first step.

**Lazy Loading**
Content Images should only load when they are scrolled into view

**Comment by Entkenntnis** [comment]
I'm happy to help here, I've have copied the design content into the storybook #27 
Using Grommet-Images, the fitting is a little bit strange

**Comment by Entkenntnis** [comment]
Content Images will be implemented in the editor, so closing this for now.
