### ISSUE TITLE
Replace classic bootstrap with styled-components lib?

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2-blue-gum#3]
Overview:
https://docs.google.com/spreadsheets/d/1wsE05sxElYVzOpPNluj_8XjqIZBe0WfcN7v1vwRzgvg/edit#gid=0

**Comment by elbotho** [comment]
@inyono how did you feel about grommet and why did you give that one a try?

**Comment by inyono** [comment]
Still trying it out. Grommet looked the most promising (regarding what's included, user base, accessibility, theming, ...). Gonna try it out for the commenting system and see how it feels working with it

**Comment by elbotho** [comment]
Thanks! OK, then I will try to convert something over to Grommet and see how I like it.
